 # KNN Imputer

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df=pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df=df[['Pclass','Age','Fare','Survived']]
df.head()

   Pclass   Age     Fare  Survived
0       3  22.0   7.2500         0
1       1  38.0  71.2833         1
2       3  26.0   7.9250         1
3       1  35.0  53.1000         1
4       3  35.0   8.0500         0

In [5]:
df.isnull().sum()

Pclass        0
Age         177
Fare          0
Survived      0
dtype: int64

In [6]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
X_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [9]:
y_train.head()

30     0
10     1
873    0
182    0
876    0
Name: Survived, dtype: int64

In [10]:
knn=KNNImputer(n_neighbors=3,weights='distance')
X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [11]:
# Convert into dataframe
pd.DataFrame(X_train_trf,columns=X_train.columns)

     Pclass        Age      Fare
0       1.0  40.000000   27.7208
1       3.0   4.000000   16.7000
2       3.0  47.000000    9.0000
3       3.0   9.000000   31.3875
4       3.0  20.000000    9.8458
..      ...        ...       ...
707     3.0  30.000000    8.6625
708     3.0  26.959410    8.7125
709     1.0  71.000000   49.5042
710     1.0  32.666667  221.7792
711     1.0  49.762895   25.9250

[712 rows x 3 columns]

In [12]:
lr=LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred=lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7039106145251397

In [13]:
# Comparision with Simple Imputer
si=SimpleImputer()

X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.transform(X_test)

In [14]:
lr.fit(X_train_trf2,y_train)
y_pred=lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred)

0.6927374301675978

In [15]:
# ======================================================================================================================================================

# Iterative Imputer

In [17]:
df=pd.read_csv("50_Startups.csv")
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [18]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [19]:
df=df.drop(columns=['State'])
df=(df/10000).round()
np.random.seed(9)
print(df.sample(5))

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [20]:

df=df.iloc[:,0:-1]
df.head()

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1       16.0            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             37.0

In [21]:
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[-1,-1]=np.nan

In [22]:
df.head()

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1        NaN            15.0             44.0
2       15.0            10.0             41.0
3       14.0             NaN             38.0
4       14.0             9.0             37.0

In [23]:
# Step1 Replace all the Nan values with mean of that column
df0=pd.DataFrame()

df0['R&D Spend']=df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration']=df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend']=df['Marketing Spend'].fillna(df['Marketing Spend'].mean())
df0=df0.round(2)
df0.head()

   R&D Spend  Administration  Marketing Spend
0      17.00           14.00             47.0
1       7.16           15.00             44.0
2      15.00           10.00             41.0
3      14.00           12.16             38.0
4      14.00            9.00             37.0

In [24]:
# Removing the col1 imputed value
df1=df0.copy()
df1.iloc[1,0]=np.nan
df1.head()

   R&D Spend  Administration  Marketing Spend
0       17.0           14.00             47.0
1        NaN           15.00             44.0
2       15.0           10.00             41.0
3       14.0           12.16             38.0
4       14.0            9.00             37.0

In [25]:
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [26]:
df1.shape

(50, 3)

In [27]:
# Using non nan rows
X=df1.iloc[[0,2,3,4],1:3]
X

   Administration  Marketing Spend
0           14.00             47.0
2           10.00             41.0
3           12.16             38.0
4            9.00             37.0

In [28]:
y=df1.iloc[[0,2,3,4],1]
y

0    14.00
2    10.00
3    12.16
4     9.00
Name: Administration, dtype: float64

In [29]:
# The model work on non nan values to predict the nan value
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\Isha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15.])

In [30]:
df1.iloc[1,0]=10

In [31]:
df1.head()

   R&D Spend  Administration  Marketing Spend
0       17.0           14.00             47.0
1       10.0           15.00             44.0
2       15.0           10.00             41.0
3       14.0           12.16             38.0
4       14.0            9.00             37.0

In [32]:
# Making the 3 row and 1 st col nan
df1.iloc[3,1]=np.nan
df1.head()

   R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1       10.0            15.0             44.0
2       15.0            10.0             41.0
3       14.0             NaN             38.0
4       14.0             9.0             37.0

In [33]:
# Now working on col2 nan value
X=df1.iloc[[0,1,2,4],[0,2]]
X

   R&D Spend  Marketing Spend
0       17.0             47.0
1       10.0             44.0
2       15.0             41.0
4       14.0             37.0

In [34]:
y=df1.iloc[[0,1,2,4],1]
y

0    14.0
1    15.0
2    10.0
4     9.0
Name: Administration, dtype: float64

In [35]:
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Isha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([9.22486486])

In [36]:
df1.iloc[3,1]=9.24

In [37]:
# After 1st iteration
df1.head()

   R&D Spend  Administration  Marketing Spend
0       17.0           14.00             47.0
1       10.0           15.00             44.0
2       15.0           10.00             41.0
3       14.0            9.24             38.0
4       14.0            9.00             37.0

In [38]:
# Substract 0th - 1st iteration
df1-df0

    R&D Spend  Administration  Marketing Spend
0        0.00            0.00              0.0
1        2.84            0.00              0.0
2        0.00            0.00              0.0
3        0.00           -2.92              0.0
4        0.00            0.00              0.0
5        0.00            0.00              0.0
6        0.00            0.00              0.0
7        0.00            0.00              0.0
8        0.00            0.00              0.0
9        0.00            0.00              0.0
10       0.00            0.00              0.0
11       0.00            0.00              0.0
12       0.00            0.00              0.0
13       0.00            0.00              0.0
14       0.00            0.00              0.0
15       0.00            0.00              0.0
16       0.00            0.00              0.0
17       0.00            0.00              0.0
18       0.00            0.00              0.0
19       0.00            0.00              0.0
20       0.00            0.00              0.0
21       0.00            0.00              0.0
22       0.00            0.00              0.0
23       0.00            0.00              0.0
24       0.00            0.00              0.0
25       0.00            0.00              0.0
26       0.00            0.00              0.0
27       0.00            0.00              0.0
28       0.00            0.00              0.0
29       0.00            0.00              0.0
30       0.00            0.00              0.0
31       0.00            0.00              0.0
32       0.00            0.00              0.0
33       0.00            0.00              0.0
34       0.00            0.00              0.0
35       0.00            0.00              0.0
36       0.00            0.00              0.0
37       0.00            0.00              0.0
38       0.00            0.00              0.0
39       0.00            0.00              0.0
40       0.00            0.00              0.0
41       0.00            0.00              0.0
42       0.00            0.00              0.0
43       0.00            0.00              0.0
44       0.00            0.00              0.0
45       0.00            0.00              0.0
46       0.00            0.00              0.0
47       0.00            0.00              0.0
48       0.00            0.00              0.0
49       0.00            0.00              0.0

In [39]:
df2=df1.copy()
df2.iloc[1,0]=np.nan
df2.head()

   R&D Spend  Administration  Marketing Spend
0       17.0           14.00             47.0
1        NaN           15.00             44.0
2       15.0           10.00             41.0
3       14.0            9.24             38.0
4       14.0            9.00             37.0

In [40]:
X=df2.iloc[[0,2,3,4],1:3]
y=df2.iloc[[0,2,3,4],0]

In [41]:
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\Isha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([16.49560806])

In [42]:
df2.iloc[1,0]=16.49

In [43]:
df2.head()

   R&D Spend  Administration  Marketing Spend
0      17.00           14.00             47.0
1      16.49           15.00             44.0
2      15.00           10.00             41.0
3      14.00            9.24             38.0
4      14.00            9.00             37.0

In [44]:
df2.iloc[3,1]=np.nan
df2.head()

   R&D Spend  Administration  Marketing Spend
0      17.00            14.0             47.0
1      16.49            15.0             44.0
2      15.00            10.0             41.0
3      14.00             NaN             38.0
4      14.00             9.0             37.0

In [45]:
X=df2.iloc[[0,1,2,4],[0,2]] 
y=df2.iloc[[0,1,2,4],1]

In [46]:
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Isha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([7.77979091])

In [47]:
df2.iloc[3,1]=7.77
df2.head()

   R&D Spend  Administration  Marketing Spend
0      17.00           14.00             47.0
1      16.49           15.00             44.0
2      15.00           10.00             41.0
3      14.00            7.77             38.0
4      14.00            9.00             37.0

In [48]:
# After iteration 2
df2-df1

    R&D Spend  Administration  Marketing Spend
0        0.00            0.00              0.0
1        6.49            0.00              0.0
2        0.00            0.00              0.0
3        0.00           -1.47              0.0
4        0.00            0.00              0.0
5        0.00            0.00              0.0
6        0.00            0.00              0.0
7        0.00            0.00              0.0
8        0.00            0.00              0.0
9        0.00            0.00              0.0
10       0.00            0.00              0.0
11       0.00            0.00              0.0
12       0.00            0.00              0.0
13       0.00            0.00              0.0
14       0.00            0.00              0.0
15       0.00            0.00              0.0
16       0.00            0.00              0.0
17       0.00            0.00              0.0
18       0.00            0.00              0.0
19       0.00            0.00              0.0
20       0.00            0.00              0.0
21       0.00            0.00              0.0
22       0.00            0.00              0.0
23       0.00            0.00              0.0
24       0.00            0.00              0.0
25       0.00            0.00              0.0
26       0.00            0.00              0.0
27       0.00            0.00              0.0
28       0.00            0.00              0.0
29       0.00            0.00              0.0
30       0.00            0.00              0.0
31       0.00            0.00              0.0
32       0.00            0.00              0.0
33       0.00            0.00              0.0
34       0.00            0.00              0.0
35       0.00            0.00              0.0
36       0.00            0.00              0.0
37       0.00            0.00              0.0
38       0.00            0.00              0.0
39       0.00            0.00              0.0
40       0.00            0.00              0.0
41       0.00            0.00              0.0
42       0.00            0.00              0.0
43       0.00            0.00              0.0
44       0.00            0.00              0.0
45       0.00            0.00              0.0
46       0.00            0.00              0.0
47       0.00            0.00              0.0
48       0.00            0.00              0.0
49       0.00            0.00              0.0

# MICE using sklearn

In [56]:
from sklearn.experimental import enable_iterative_imputer

from sklearn.impute import IterativeImputer

In [62]:
data=np.array([
    [1,2,np.nan],
    [np.nan,4,7],
    [8,np.nan,10]
])

In [70]:
imputer=IterativeImputer(max_iter=10,random_state=0)
X=imputer.fit_transform(data)
print(X)

[[ 1.          2.          7.8039215 ]
 [-1.56256453  4.          7.        ]
 [ 8.         -3.46364971 10.        ]]

In [72]:
pd.DataFrame(X)

          0        1          2
0  1.000000  2.00000   7.803922
1 -1.562565  4.00000   7.000000
2  8.000000 -3.46365  10.000000